#!/bin/sh

"$HOME/.config/polybar/launch"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -r '*'
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
