#!/bin/sh
bspwm_dir="$(dirname -- "$(readlink -f -- "$0")")"

"${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch" &
"$bspwm_dir/launch_watchers" &

# From scripts repo
distribute_monitors

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -r '*'
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc config external_rules_command "$bspwm_dir/external_rules"
