#!/bin/sh
# Terminate already running bar instances
polybar-msg cmd quit

# Launch bars
for bar in main bspwm; do
	echo "---" | tee -a /tmp/polybar-$bar.log
	polybar $bar 2>&1 | tee -a /tmp/polybar-$bar.log &
done
